// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjQmme3dBOR_0A6Vrc0YkgwoKkCgGYEW8',
    appId: '1:167100424418:web:62ded6d94554aac5c43ebb',
    messagingSenderId: '167100424418',
    projectId: 'safestreet-96f7d',
    authDomain: 'safestreet-96f7d.firebaseapp.com',
    storageBucket: 'safestreet-96f7d.firebasestorage.app',
    measurementId: 'G-959WL458DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjClZrADjBwIzcyc9fIiiBke7BQ3ICAY',
    appId: '1:167100424418:android:2abf2f2c73cca3f2c43ebb',
    messagingSenderId: '167100424418',
    projectId: 'safestreet-96f7d',
    storageBucket: 'safestreet-96f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJwnvc09kKZjuwl0wlJmsatOFUSh9AKk',
    appId: '1:167100424418:ios:7ed68b2d41957349c43ebb',
    messagingSenderId: '167100424418',
    projectId: 'safestreet-96f7d',
    storageBucket: 'safestreet-96f7d.firebasestorage.app',
    iosBundleId: 'com.example.safestreetFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJwnvc09kKZjuwl0wlJmsatOFUSh9AKk',
    appId: '1:167100424418:ios:7ed68b2d41957349c43ebb',
    messagingSenderId: '167100424418',
    projectId: 'safestreet-96f7d',
    storageBucket: 'safestreet-96f7d.firebasestorage.app',
    iosBundleId: 'com.example.safestreetFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjQmme3dBOR_0A6Vrc0YkgwoKkCgGYEW8',
    appId: '1:167100424418:web:25d062febe19275dc43ebb',
    messagingSenderId: '167100424418',
    projectId: 'safestreet-96f7d',
    authDomain: 'safestreet-96f7d.firebaseapp.com',
    storageBucket: 'safestreet-96f7d.firebasestorage.app',
    measurementId: 'G-RLC12K1415',
  );
}
